"""cultivo sin dias

Revision ID: 89cde01cd0a5
Revises: e85995d6b143
Create Date: 2026-03-12 11:22:54.882855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89cde01cd0a5'
down_revision: Union[str, None] = 'e85995d6b143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones_herramientas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herramienta_id', sa.Integer(), nullable=True),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herramienta_id'], ['herramientas.id'], ),
    sa.ForeignKeyConstraint(['labor_id'], ['labores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_herramientas_id'), 'asignaciones_herramientas', ['id'], unique=False)
    op.add_column('diagnosticos', sa.Column('tipo', sa.String(length=100), nullable=False))
    op.add_column('diagnosticos', sa.Column('estudiante_id', sa.Integer(), nullable=True))
    op.add_column('diagnosticos', sa.Column('docente_id', sa.Integer(), nullable=True))
    op.add_column('diagnosticos', sa.Column('lote_id', sa.Integer(), nullable=True))
    op.add_column('diagnosticos', sa.Column('estado', sa.String(length=50), nullable=True))
    op.add_column('diagnosticos', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('diagnosticos', sa.Column('fecha_revision', sa.DateTime(), nullable=True))
    op.add_column('diagnosticos', sa.Column('observaciones', sa.Text(), nullable=True))
    op.create_index(op.f('ix_diagnosticos_id'), 'diagnosticos', ['id'], unique=False)
    op.create_foreign_key(None, 'diagnosticos', 'usuarios', ['estudiante_id'], ['id'])
    op.create_foreign_key(None, 'diagnosticos', 'usuarios', ['docente_id'], ['id'])
    op.create_foreign_key(None, 'diagnosticos', 'lotes', ['lote_id'], ['id'])
    op.drop_column('diagnosticos', 'nombre')
    op.drop_column('diagnosticos', 'fecha')
    op.drop_column('diagnosticos', 'created_at')
    op.drop_column('diagnosticos', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosticos', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'diagnosticos', type_='foreignkey')
    op.drop_constraint(None, 'diagnosticos', type_='foreignkey')
    op.drop_constraint(None, 'diagnosticos', type_='foreignkey')
    op.drop_index(op.f('ix_diagnosticos_id'), table_name='diagnosticos')
    op.drop_column('diagnosticos', 'observaciones')
    op.drop_column('diagnosticos', 'fecha_revision')
    op.drop_column('diagnosticos', 'fecha_creacion')
    op.drop_column('diagnosticos', 'estado')
    op.drop_column('diagnosticos', 'lote_id')
    op.drop_column('diagnosticos', 'docente_id')
    op.drop_column('diagnosticos', 'estudiante_id')
    op.drop_column('diagnosticos', 'tipo')
    op.drop_index(op.f('ix_asignaciones_herramientas_id'), table_name='asignaciones_herramientas')
    op.drop_table('asignaciones_herramientas')
    # ### end Alembic commands ###
